services:
  app:
    image: ghcr.io/crediblemark-official/tertaut.com:latest
    container_name: tertaut_app
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3001}
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL wajib diisi}
      PUBLIC_APP_URL: ${PUBLIC_APP_URL:-}
      JWT_SECRET: ${JWT_SECRET:-}
      VAULT_ENCRYPTION_KEY: ${VAULT_ENCRYPTION_KEY:-}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-}
      LICENSE_SIGNING_PRIVATE_KEY: ${LICENSE_SIGNING_PRIVATE_KEY:-}
      HWID_SALT: ${HWID_SALT:-}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      MAIL_FROM: ${MAIL_FROM:-}
      EMAIL_REPLY_TO: ${EMAIL_REPLY_TO:-}
      PAYMENT_GATEWAY: ${PAYMENT_GATEWAY:-dana}
      DANA_ENV: ${DANA_ENV:-production}
      DANA_ORIGIN: ${DANA_ORIGIN:-}
      DANA_CLIENT_ID: ${DANA_CLIENT_ID:-}
      DANA_CLIENT_SECRET: ${DANA_CLIENT_SECRET:-}
      DANA_MERCHANT_ID: ${DANA_MERCHANT_ID:-}
      DANA_BASE_URL: ${DANA_BASE_URL:-https://api.saas.dana.id}
      DANA_PUBLIC_KEY: ${DANA_PUBLIC_KEY:-}
      DANA_PRIVATE_KEY: ${DANA_PRIVATE_KEY:-}
      DANA_SANDBOX_CLIENT_ID: ${DANA_SANDBOX_CLIENT_ID:-}
      DANA_SANDBOX_CLIENT_SECRET: ${DANA_SANDBOX_CLIENT_SECRET:-}
      DANA_SANDBOX_MERCHANT_ID: ${DANA_SANDBOX_MERCHANT_ID:-}
      DANA_SANDBOX_BASE_URL: ${DANA_SANDBOX_BASE_URL:-https://api.sandbox.dana.id}
      DANA_SANDBOX_PUBLIC_KEY: ${DANA_SANDBOX_PUBLIC_KEY:-}
      DANA_SANDBOX_PRIVATE_KEY: ${DANA_SANDBOX_PRIVATE_KEY:-}
      BUN_LOG_SCOPE: "*"
      BUN_JSX_RUNTIME: "haste"
    ports:
      - "${APP_PORT:-3001}:3001"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 128M
          cpus: "0.25"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT:-3001}/api/v1/health || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 20s
      retries: 3
